#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
umask 077
if ! command -v docker >/dev/null 2>&1; then
  echo 'Docker CLI가 없습니다. OrbStack을 설치하고 시작하세요.' >&2
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  echo 'Docker 엔진에 연결할 수 없습니다. OrbStack을 먼저 시작하세요.' >&2
  exit 1
fi
if [[ ! -e .env.db.local ]]; then
  node --input-type=module <<'NODE'
import { randomBytes } from 'node:crypto';
import { writeFileSync } from 'node:fs';
const admin = randomBytes(32).toString('hex');
const app = randomBytes(32).toString('hex');
writeFileSync('.env.db.local', `POSTGRES_PASSWORD=${admin}\nTORIS_DB_APP_PASSWORD=${app}\nTORIS_DB_PORT=54329\n`, { mode: 0o600, flag: 'wx' });
NODE
fi
chmod 600 .env.db.local
node --input-type=module <<'NODE'
import { parseEnv } from 'node:util';
import { readFileSync, appendFileSync, chmodSync } from 'node:fs';
const settings = parseEnv(readFileSync('.env.db.local', 'utf8'));
if (!settings.TORIS_DB_APP_PASSWORD || !settings.POSTGRES_PASSWORD) throw new Error('DB local credentials are incomplete');
let existing = '';
try { existing = readFileSync('.env.local', 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
if (!/^\s*(?:export\s+)?DATABASE_URL\s*=/m.test(existing)) {
  const url = `postgresql://toris_app:${encodeURIComponent(settings.TORIS_DB_APP_PASSWORD)}@127.0.0.1:${settings.TORIS_DB_PORT ?? '54329'}/toris_studio`;
  appendFileSync('.env.local', `\n# Local PostgreSQL, generated by db:start\nDATABASE_URL=${url}\n`, { mode: 0o600 });
}
chmodSync('.env.local', 0o600);
NODE
docker compose --env-file .env.db.local up -d --wait postgres
echo '로컬 PostgreSQL 준비 완료. 기존 .env.local을 보존했습니다. 개발 서버를 다시 시작하면 DB에 연결됩니다.'
